config/routes.rb
Rails.application.routes.draw do
  resources :fundings
  root "home#index"
  resources :passwords, param: :token
  get "home/index"
  resources :movies do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :series do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :actors do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :register, only: [:new, :create]
  resource :session
  
  get 'movies/:id/download_pdf', to: 'documents#download_pdf', as: :download_pdf
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'
  post '/stripe_webhooks/webhook', to: 'stripe_webhooks#webhook'


  get "comments", to: "comments#index"
  get "search", to: "search#index"
  get 'suggestions', to: 'search#suggestions'

  get 'chat', to: 'chat#index'
  resource :chat_responses
  resource :search_responses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/actor.rb
class Actor < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :surname, presence: true, length: { minimum: 2, maximum: 50 }
  validates :date_of_birth, presence: true
  validates :place_of_birth, presence: true
  validates :height, numericality: { only_integer: true, greater_than: 50, less_than: 250 }
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  has_one_attached :my_file
  has_many :comments, dependent: :destroy
  validates :image_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: "must be a valid URL" }, allow_blank: true
    ["name", "surname", "rating"]

  has_and_belongs_to_many :movies
  has_and_belongs_to_many :series
  end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :release_date, presence: true
  validates :length, numericality: { only_integer: true, greater_than: 30, less_than: 300 }
  validates :category, presence: true
  has_one_attached :my_file
  validates :image_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: "must be a valid URL" }, allow_blank: true

  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :actors

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "length", "rating", "release_date", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_actor, only: %i[ show edit update destroy ]

  # GET /actors or /actors.json
  def index
    # @actors = Actor.all
    @actors = Actor.page(params[:page]).per(6)
  end

  # GET /actors/1 or /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors or /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: "Actor was successfully created." }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1 or /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: "Actor was successfully updated." }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1 or /actors/1.json
  def destroy
    @actor.destroy!

    respond_to do |format|
      format.html { redirect_to actors_path, status: :see_other, notice: "Actor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.expect(actor: [ :name, :surname, :date_of_birth, :place_of_birth, :height, :rating, :image_url, :my_file, :trailer_url ])
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_actor.html.slim
div id="#{dom_id actor}"
 div.collectionItemContainer
    = image_tag actor.my_file.attached? ? url_for(actor.my_file) : actor.image_url, class:"collectionItemThumbnail"
    div.collectionItemTextContainer
      p.collectionItemTitle
        =< "#{actor.name} #{actor.surname}"
      div.collectionItemData
        p.collectionItemRating
          strong Rating:
          =< "#{actor.rating} / 10.0"
        p.collectionItemDate
          strong Date of birth: 
          =< actor.date_of_birth
        p.collectionItemDate
          strong Place of birth: 
          =< actor.place_of_birth
        p.collectionItemHeight
          strong Height:
          =< "#{actor.height} min"
      / div.collectionItemButtonContainer
      /   => link_to "Edit this actor", edit_actor_path(actor),  class:"collectionItemEditButton" if authenticated?
      /   = button_to "Destroy this actor", @actor, method: :delete, class:"collectionItemDeleteButton" if authenticated?

app/views/actors/_form.html.slim
= form_with(model: actor) do |form|
  - if actor.errors.any?
    div style="color: red"
      h2 = "#{pluralize(actor.errors.count, "error")} prohibited this actor from being saved:"
      ul
        - actor.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :surname, style: "display: block"
    = form.text_field :surname

  div
    = form.label :date_of_birth, style: "display: block"
    = form.date_field :date_of_birth

  div
    = form.label :place_of_birth, style: "display: block"
    = form.text_field :place_of_birth

  div
    = form.label :height, style: "display: block"
    = form.number_field :height

  div id="actors"
    - @actors_count.times do |index|
      div class="actor-select" id="actor_#{index}"
        = form.collection_select :actor_ids, Actor.all, :id, :name, { include_blank: true }, { class: 'form-control' }

  div
    = link_to "Add Actor", new_movie_path(actor: true), class: 'btn btn-primary'

  div
    = form.file_field :my_file

  div
    = form.submit

app/views/actors/edit.html.slim
h1 Editing actor

== render "form", actor: @actor

br

div
  => link_to "Show this actor", @actor
  '|
  =< link_to "Back to actors", actors_path

app/views/actors/index.html.slim
p style="color: green" = notice

div.container
  ul.collectionList
    - @actors.each do |actor|
      li 
        = link_to actor_path(actor) do
          .collectionItem
            = image_tag actor.my_file.attached? ? url_for(actor.my_file) : actor.image_url, class:"collectionThumbnail"
            h4.collectionTitle = "#{actor.name} #{actor.surname}"
            p.collectionRating = "#{actor.rating} / 10" 

  / button.addNewButton = link_to "+ Add new actor", new_actor_path
  = paginate @actors

app/views/actors/new.html.slim
h1 New actor

== render "form", actor: @actor

br

div
  = link_to "Back to actors", actors_path

app/views/actors/show.html.slim
p style="color: green" = notice
div.container
  = link_to actors_path, class: "backButton" do
      = image_tag 'back.svg', alt: "Back to movies", class: "backIcon"
    
  == render @actor
  
  div.commentsContainer
    h3.commentsTitle = "Comments #{Comment.where(actor_id: @actor.id).count}" 
    ul.commentsItemList
      - @actor.comments.each do |comment|
        li.commentsItem
          div.commentsUserContainer
            = image_tag "/images/user.png", class:"userAvatar"
            p.commentsAuthor = comment.user.email_address
          div.commentsText = comment.content
          p.commentsCreatedAt = comment.created_at.strftime("%Y-%m-%d %H:%M")
    = form_with(model:[@actor, Comment.new]) do |form|  
      p
        = form.text_area :content, class:"commentsTextArea"
      p
        = form.submit "Add comment", class:"addNewButton"
  