config/routes.rb
Rails.application.routes.draw do
  resources :fundings
  root "home#index"
  resources :passwords, param: :token
  get "home/index"
  resources :movies do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :series do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :actors do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :register, only: [:new, :create]
  resource :session
  
  get 'movies/:id/download_pdf', to: 'documents#download_pdf', as: :download_pdf
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'
  post '/stripe_webhooks/webhook', to: 'stripe_webhooks#webhook'


  get "comments", to: "comments#index"
  get "search", to: "search#index"
  get 'suggestions', to: 'search#suggestions'

  get 'chat', to: 'chat#index'
  resource :chat_responses
  resource :search_responses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :release_date, presence: true
  validates :length, numericality: { only_integer: true, greater_than: 30, less_than: 300 }
  validates :category, presence: true
  has_one_attached :my_file
  validates :image_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: "must be a valid URL" }, allow_blank: true

  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :actors

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "length", "rating", "release_date", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    # @movies = Movie.all
    @movies = Movie.page(params[:page]).per(6)
  end

  # GET /movies/1 or /movies/1.json
  def show
    @actors = @movie.actors
    @comments = @movie.comments
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy!

    respond_to do |format|
      format.html { redirect_to movies_path, status: :see_other, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.expect(movie: [ :title, :description, :rating, :release_date, :length, :category, :director, :image_url ,:my_file, :trailer_url, actor_ids: [] ])
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.slim
= form_with(model: movie) do |form|
  - if movie.errors.any?
    div style="color: red"
      h2 = "#{pluralize(movie.errors.count, "error")} prohibited this movie from being saved:"
      ul
        - movie.errors.each do |error|
          li = error.full_message

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :description, style: "display: block"
    = form.textarea :description

  div
    = form.label :rating, style: "display: block"
    = form.text_field :rating

  div
    = form.label :release_date, style: "display: block"
    = form.date_field :release_date

  div
    = form.label :length, style: "display: block"
    = form.text_field :length

  div
    = form.label :category, style: "display: block"
    = form.text_field :category
    
  div
    = form.label :director, style: "display: block"
    = form.text_field :director

  div
    = form.file_field :my_file

  div
    = form.label :actors, "Select Actors", style: "display: block"
    = form.select :actor_ids, Actor.all.collect { |actor| ["#{actor.name} #{actor.surname}", actor.id] }, { multiple: true}

  div
    = form.submit

app/views/movies/_movie.html.slim
= stylesheet_link_tag 'collection_item', media: 'css'

div.collectionItemSection id="#{dom_id(movie)}"
  div.collectionItemContainer
    = image_tag movie.my_file.attached? ? url_for(movie.my_file) : movie.image_url, class: "collectionItemThumbnail"
    div.collectionItemTextContainer
      h4.collectionItemTitle
        = movie.title.upcase
      div.collectionItemText
        div.collectionItemText--left
          div.collectionItemCategoryContainer
            p.collectionItemCategory
              = movie.category
            p.collectionItemCategory
              = movie.category
            p.collectionItemCategory
              = movie.category
          div.collectionItemData
            p.collectionItemRating
              = image_tag "star.svg", class: "collectionItemStar"
              = movie.rating
            p.collectionItemDescription
              = movie.description
          div.collectionItemButtonContainer
            = link_to "EDIT THIS MOVIE", edit_movie_path(@movie), class: "collectionItemButton" if authenticated?
            = button_to "DELETE THIS MOVIE", @movie, method: :delete, class: "collectionItemButton--secondary" if authenticated?
          = link_to "Download PDF", download_pdf_path(movie)
        div.collectionItemText--right
          h5.collectionItemTextHeader Release Date
          p.collectionItemRight = movie.release_date
          h5.collectionItemTextHeader Length
          p.collectionItemRight = "#{movie.length} min"
          h5.collectionItemTextHeader Director
          p.collectionItemRight = movie.director
            

app/views/movies/edit.html.slim
h1 Editing movie

== render "form", movie: @movie

br

div
  => link_to "Show this movie", @movie
  '|
  =< link_to "Back to movies", movies_path

app/views/movies/index.html.slim
= stylesheet_link_tag 'collection', media: 'css'

p style="color: green" = notice
.container
  ul.collectionList
    - @movies.each do |movie|
      li
        = link_to movie_path(movie) do
          .collectionItem
            = image_tag movie.my_file.attached? ? url_for(movie.my_file) : movie.image_url, class:"collectionThumbnail"
            h4.collectionTitle = movie.title
            p.collectionCategory = "#{movie.category} | #{movie.release_date}"
  button.addNewButton = link_to "+ Add new movie", new_movie_path
  = paginate @movies

app/views/movies/new.html.slim
h1 New movie

== render "form", movie: @movie

br

div
  = link_to "Back to movies", movies_path

app/views/movies/show.html.slim
p style="color: green" = notice


.container
  = link_to movies_path, class: "backButton" do
    = image_tag 'back.svg', alt: "Back to movies", class: "backIcon"
  == render @movie
  
  div.actorsContainer
    h3.headerTitle Actors
    ul.actorsList 
      - @actors.each do |actor|
        li 
          =link_to actor do
            = image_tag actor.my_file.attached? ? url_for(actor.my_file) : actor.image_url, class:"actorThumbnail"
            span = actor.name + " " + actor.surname
            p = actor.rating

  = render 'comments/index', locals: { movie: @movie }