config/routes.rb
Rails.application.routes.draw do
  resources :fundings
  root "home#index"
  resources :passwords, param: :token
  get "home/index"
  resources :movies do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :series do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :actors do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :register, only: [:new, :create]
  resource :session
  
  get 'movies/:id/download_pdf', to: 'documents#download_pdf', as: :download_pdf
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'
  post '/stripe_webhooks/webhook', to: 'stripe_webhooks#webhook'


  get "comments", to: "comments#index"
  get "search", to: "search#index"
  get 'suggestions', to: 'search#suggestions'

  get 'chat', to: 'chat#index'
  resource :chat_responses
  resource :search_responses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/funding.rb
class Funding < ApplicationRecord
  belongs_to :user
  has_many :payment
  has_many :contributors, through: :payments, source: :user
end

app/controllers/fundings_controller.rb
class FundingsController < ApplicationController
  before_action :set_funding, only: %i[ show edit update destroy ]

  # GET /fundings or /fundings.json
  def index
    Stripe.api_key = Rails.application.credentials.dig(:stripe, :secret_key)

    @fundings = Funding.all
    @objects = Stripe::Product.list({limit: 3})
    @payments_amounts = Payment.group(:funding_id).sum(:amount) || {}
  end

  # GET /fundings/1 or /fundings/1.json
  def show
    Stripe.api_key = Rails.application.credentials.dig(:stripe, :secret_key)

    @funding = Funding.find(params[:id])
    @payments = Payment.where(funding_id: @funding.id)
    @payments_amounts = Payment.group(:funding_id).sum(:amount) || {}
    @payments_counter = @payments.count
    @payments_user = User.joins(:payments).where(payments: { funding_id: @funding.id }).select("users.email_address, payments.amount")
    @stripe_product = Stripe::Product.retrieve(@funding.stripe_product_id)
    @stripe_price = @stripe_product.default_price
    
    @checkout_session = current_user
      .payment_processor
      .checkout(
        mode: 'payment',
        line_items: [{ price: @stripe_price, quantity: 1 }],
        success_url: "#{checkout_success_url}?funding_id=#{@funding.id}",
        metadata: { funding_id: @funding.id, user_id: current_user.id }
      )
  end
  

  # GET /fundings/new
  def new
    @funding = Funding.new
  end

  # GET /fundings/1/edit
  def edit
  end

  # POST /fundings or /fundings.json
  def create
    @funding = Funding.new(funding_params)
    @funding.user = current_user

    
    if @funding.save
      stripe_product = Stripe::Product.create({
        name: @funding.title,
        description: @funding.description,
        images:  ['https://www.science.org/do/10.1126/science.opms.aav3708/abs/14septfacultylead.jpg'],
        default_price_data: {
          currency: 'pln',
          unit_amount:(@funding.stripe_single_price.to_f * 100).to_i
        }
      })

      @funding.update(stripe_product_id: stripe_product.id)
      @funding.update(image_url: 'https://www.science.org/do/10.1126/science.opms.aav3708/abs/14septfacultylead.jpg')
    end 

    respond_to do |format|
      if @funding.save
        format.html { redirect_to @funding, notice: "Funding was successfully created." }
        format.json { render :show, status: :created, location: @funding }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fundings/1 or /fundings/1.json
  def update
    respond_to do |format|
      if @funding.update(funding_params)
        format.html { redirect_to @funding, notice: "Funding was successfully updated." }
        format.json { render :show, status: :ok, location: @funding }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fundings/1 or /fundings/1.json
  def destroy
    @funding.destroy!

    respond_to do |format|
      format.html { redirect_to fundings_path, status: :see_other, notice: "Funding was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funding
      @funding = Funding.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def funding_params
      params.require(:funding).permit( :title, :description, :goal_amount, :user_id, :image_url, :stripe_single_price )
    end
end

app/helpers/fundings_helper.rb
module FundingsHelper
end

app/views/fundings/_form.html.slim
= form_with(model: funding) do |form|
  - if funding.errors.any?
    div style="color: red"
      h2 = "#{pluralize(funding.errors.count, "error")} prohibited this funding from being saved:"
      ul
        - funding.errors.each do |error|
          li = error.full_message

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :description, style: "display: block"
    = form.textarea :description

  div
    = form.label :goal_amount, style: "display: block"
    = form.text_field :goal_amount

  div
    = form.label :stripe_single_price, style: "display: block"
    = form.text_field :stripe_single_price
  / div
  /   = form.file_field :my_file

  div
    = form.submit

app/views/fundings/_funding.html.slim
div id="#{dom_id funding}"
  div.fundingItemContainer
    - total_payments = @payments_amounts[funding.id].to_f
    - progress_percentage = (total_payments / funding.goal_amount * 100).clamp(0, 100)

    div.fundingItemMain
      = image_tag url_for(funding.image_url), class: "fundingItemImage"
      div.fundingItemDescription
        h4.headerFunding = funding.title
        p.fundingItemDescription = funding.description

    aside.fundingItemAside
      div.fundingItemDeposit
        div.fundingItemTarget
          span.fundingItemTargetText = "#{total_payments.to_i} PLN"
          span.fundingItemTargetTextSecondary = " z #{funding.goal_amount.to_i} PLN"
        div.progress
          div.progressBar style="width: #{progress_percentage}%"
        = link_to "Checkout", @checkout_session.url, class: "btn btnCheckout"
      div.fundingItemAuthor
        div.fundingItemAuthorContainer
          = image_tag "/images/user.png", class:"userAvatar"
          p = funding.user.email_address
          p  Funding author
      div.fundingItemPayments
        p = "Donations: #{@payments_counter}"
        ul.paymentsList
          - @payments_user.each do |user|
            li
              = image_tag "/images/user.png", class:"userAvatar"
              div
                p = user.email_address
                p = "#{user.amount} zł"

app/views/fundings/edit.html.slim
h1 Editing funding

== render "form", funding: @funding

br

div
  => link_to "Show this funding", @funding
  '|
  =< link_to "Back to fundings", fundings_path

app/views/fundings/index.html.slim
div.container.fundingsContainer
  p style="color: green" = notice

  h1.headerTitle Fundings

  #fundings
    ul.fundingsList
      - @fundings.each do |funding|
        - total_payments = @payments_amounts[funding.id].to_f
        - progress_percentage = (total_payments / funding.goal_amount * 100).clamp(0, 100) 
        li.fundingsItem
          = link_to funding_path(funding) do
            = image_tag url_for(funding.image_url), class: "fundingImage"
            div.fundingTextContainer
              p.headerFunding = "#{funding.goal_amount.to_i} PLN"
              h4.subheaderFunding = funding.title
              div.progress
                div.progressBar style="width: #{progress_percentage}%"
              p.fundingDescription = funding.description

  = link_to "New funding", new_funding_path

app/views/fundings/new.html.slim
h1 New funding

== render "form", funding: @funding

br

div
  = link_to "Back to fundings", fundings_path

app/views/fundings/show.html.slim
p style="color: green" = notice


div.container.firstContainer
  =< link_to "Back to fundings", fundings_path
  
  == render @funding
  


  / => link_to "Edit this funding", edit_funding_path(@funding)


  / = button_to "Destroy this funding", @funding, method: :delete