config/routes.rb
Rails.application.routes.draw do
  resources :fundings
  root "home#index"
  resources :passwords, param: :token
  get "home/index"
  resources :movies do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :series do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :actors do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :register, only: [:new, :create]
  resource :session
  
  get 'movies/:id/download_pdf', to: 'documents#download_pdf', as: :download_pdf
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'
  post '/stripe_webhooks/webhook', to: 'stripe_webhooks#webhook'


  get "comments", to: "comments#index"
  get "search", to: "search#index"
  get 'suggestions', to: 'search#suggestions'

  get 'chat', to: 'chat#index'
  resource :chat_responses
  resource :search_responses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :release_date, presence: true
  validates :length, numericality: { only_integer: true, greater_than: 30, less_than: 300 }
  validates :category, presence: true
  has_one_attached :my_file
  validates :image_url, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: "must be a valid URL" }, allow_blank: true

  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :actors

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "length", "rating", "release_date", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    # @series = Series.all
    @series = Series.page(params[:page]).per(6)
  end

  # GET /series/1 or /series/1.json
  def show
    @actors = @series.actors
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy!

    respond_to do |format|
      format.html { redirect_to series_index_path, status: :see_other, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.expect(series: [ :title, :description, :rating, :release_date, :no_of_seasons, :category, :director ,:image_url, :my_file, :trailer_url, actor_ids: [] ])
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.slim
= form_with(model: series) do |form|
  - if series.errors.any?
    div style="color: red"
      h2 = "#{pluralize(series.errors.count, "error")} prohibited this series from being saved:"
      ul
        - series.errors.each do |error|
          li = error.full_message

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :description, style: "display: block"
    = form.textarea :description

  div
    = form.label :rating, style: "display: block"
    = form.text_field :rating

  div
    = form.label :release_date, style: "display: block"
    = form.date_field :release_date

  div
    = form.label :no_of_seasons, style: "display: block"
    = form.number_field :no_of_seasons

  div
    = form.label :category, style: "display: block"
    = form.text_field :category
  

   div
    = form.label :director, style: "display: block"
    = form.text_field :director

  div
    = form.file_field :my_file

  div
    = form.label :actors, "Select Actors"
    = form.select :actor_ids, Actor.all.collect { |actor| ["#{actor.name} #{actor.surname}", actor.id] }, { multiple: true}

  div
    = form.submit

app/views/series/_series.html.slim
div.collectionItemSection id="#{dom_id(series)}"
  div.collectionItemContainer
    = image_tag series.my_file.attached? ? url_for(series.my_file) : series.image_url, class: "collectionItemThumbnail"
    div.collectionItemTextContainer
      h4.collectionItemTitle
        = series.title.upcase
      div.collectionItemText
        div.collectionItemText--left
          div.collectionItemCategoryContainer
            p.collectionItemCategory
              = series.category
            p.collectionItemCategory
              = series.category
            p.collectionItemCategory
              = series.category
          div.collectionItemData
            p.collectionItemRating
              = image_tag "star.svg", class: "collectionItemStar"
              = series.rating
            p.collectionItemDescription
              = series.description
          div.collectionItemButtonContainer
            = link_to "EDIT THIS SERIES", edit_series_path(@series), class: "collectionItemButton" if authenticated?
            = button_to "DELETE THIS SERIES", @series, method: :delete, class: "collectionItemButton--secondary" if authenticated?
        div.collectionItemText--right
          h5.collectionItemTextHeader Release Date
          p.collectionItemRight = series.release_date
          h5.collectionItemTextHeader Number of seasons
          p.collectionItemRight = "#{series.no_of_seasons} min"
          h5.collectionItemTextHeader Director
          p.collectionItemRight = series.director
          

app/views/series/edit.html.slim
h1 Editing series

== render "form", series: @series

br

div
  => link_to "Show this series", @series
  '|
  =< link_to "Back to series", series_index_path

app/views/series/index.html.slim
= stylesheet_link_tag 'collection', media: 'css'

p style="color: green" = notice

.container
  ul.collectionList
    - @series.each do |serie|
      li
        = link_to series_path(serie) do
          .collectionItem
            = image_tag serie.my_file.attached? ? url_for(serie.my_file) : serie.image_url, class:"collectionThumbnail"
            h4.collectionTitle = serie.title
            p.collectionCategory = "#{serie.category} | #{serie.release_date}"
  button.addNewButton = link_to "+ Add new series", new_series_path
  = paginate @series

app/views/series/new.html.slim
h1 New series

== render "form", series: @series

br

div
  = link_to "Back to series", series_index_path

app/views/series/show.html.slim
p style="color: green" = notice

.container
  = link_to series_index_path, class: "backButton" do
      = image_tag 'back.svg', alt: "Back to movies", class: "backIcon"
  == render @series

  div.actorsContainer
    ul.actorsList 
      - @actors.each do |actor|
        li 
          =link_to actor do
            = image_tag actor.my_file.attached? ? url_for(actor.my_file) : actor.image_url, class:"actorThumbnail"
            h4 = actor.name + " " + actor.surname
            p = actor.rating

  div.commentsContainer
    h3.commentsTitle = "Comments #{Comment.where(series_id: @series.id).count}" 
    ul.commentsItemList
      - @series.comments.each do |comment|
        li.commentsItem
          div.commentsUserContainer
            = image_tag "/images/user.png", class:"userAvatar"
            p.commentsAuthor = comment.user.email_address
          div.commentsText = comment.content
          p.commentsCreatedAt = comment.created_at.strftime("%Y-%m-%d %H:%M")
    = form_with(model:[@series, Comment.new]) do |form|  
      p
        = form.text_area :content, class:"commentsTextArea"
      p
        = form.submit "Add comment", class:"addNewButton"